# Site settings
baseurl = "https://waynewitzel.com/"
languageCode = "en-us"
disqusShortname = "waynewitzel"
title = "waynewitzel.com"
theme = "ghostwriter"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[author]
    name = "Wayne Witzel III"
    profile = "/page/about/"

[params]
    intro = true
    headline = "random ramblings"
	description = "trying to computer and life"
    twitter  = "https://www.twitter.com/wwitzel3"
    linkedin = "https://www.linkedin.com/in/wwitzel3"
    github   = "https://www.github.com/wwitzel3"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
