baseurl = "http://waynewitzel.com"
languageCode = "en-us"
title = "random technology ramblings"
disqusShortname = "waynewitzel"
socialSharing = true

[params]
    brandname = "Wayne Witzel III"

[[menu.social]]
	pre = "<i class='fa fa-twitter'></i>"
    url = "http://www.twitter.com/wwitzel3"
    identifier = "twitter"

[permalinks]
    post = "/:year/:month/:day/:title/"
    top = "/:filename"
